# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asignacion_aula_7_pb2 as asignacion__aula__7__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in asignacion_aula_7_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EstudianteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerEstudiante = channel.unary_unary(
                '/EstudianteService/ObtenerEstudiante',
                request_serializer=asignacion__aula__7__pb2.EstudianteRequest.SerializeToString,
                response_deserializer=asignacion__aula__7__pb2.EstudianteReply.FromString,
                _registered_method=True)
        self.ListarEstudiantes = channel.unary_unary(
                '/EstudianteService/ListarEstudiantes',
                request_serializer=asignacion__aula__7__pb2.Empty.SerializeToString,
                response_deserializer=asignacion__aula__7__pb2.EstudianteList.FromString,
                _registered_method=True)
        self.CrearEstudiante = channel.unary_unary(
                '/EstudianteService/CrearEstudiante',
                request_serializer=asignacion__aula__7__pb2.EstudianteReply.SerializeToString,
                response_deserializer=asignacion__aula__7__pb2.EstudianteReply.FromString,
                _registered_method=True)
        self.BorrarEstudiante = channel.unary_unary(
                '/EstudianteService/BorrarEstudiante',
                request_serializer=asignacion__aula__7__pb2.EstudianteRequest.SerializeToString,
                response_deserializer=asignacion__aula__7__pb2.DeleteResponse.FromString,
                _registered_method=True)


class EstudianteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarEstudiantes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrarEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstudianteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstudiante,
                    request_deserializer=asignacion__aula__7__pb2.EstudianteRequest.FromString,
                    response_serializer=asignacion__aula__7__pb2.EstudianteReply.SerializeToString,
            ),
            'ListarEstudiantes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarEstudiantes,
                    request_deserializer=asignacion__aula__7__pb2.Empty.FromString,
                    response_serializer=asignacion__aula__7__pb2.EstudianteList.SerializeToString,
            ),
            'CrearEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearEstudiante,
                    request_deserializer=asignacion__aula__7__pb2.EstudianteReply.FromString,
                    response_serializer=asignacion__aula__7__pb2.EstudianteReply.SerializeToString,
            ),
            'BorrarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrarEstudiante,
                    request_deserializer=asignacion__aula__7__pb2.EstudianteRequest.FromString,
                    response_serializer=asignacion__aula__7__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EstudianteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EstudianteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EstudianteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstudianteService/ObtenerEstudiante',
            asignacion__aula__7__pb2.EstudianteRequest.SerializeToString,
            asignacion__aula__7__pb2.EstudianteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarEstudiantes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstudianteService/ListarEstudiantes',
            asignacion__aula__7__pb2.Empty.SerializeToString,
            asignacion__aula__7__pb2.EstudianteList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstudianteService/CrearEstudiante',
            asignacion__aula__7__pb2.EstudianteReply.SerializeToString,
            asignacion__aula__7__pb2.EstudianteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstudianteService/BorrarEstudiante',
            asignacion__aula__7__pb2.EstudianteRequest.SerializeToString,
            asignacion__aula__7__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
