# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asignacion-aula-7.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'asignacion-aula-7.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61signacion-aula-7.proto\"&\n\x11\x45studianteRequest\x12\x11\n\tmatricula\x18\x01 \x01(\x05\"4\n\x0f\x45studianteReply\x12\x11\n\tmatricula\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"7\n\x0e\x45studianteList\x12%\n\x0b\x65studiantes\x18\x01 \x03(\x0b\x32\x10.EstudianteReply\"0\n\x0e\x44\x65leteResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xec\x01\n\x11\x45studianteService\x12\x39\n\x11ObtenerEstudiante\x12\x12.EstudianteRequest\x1a\x10.EstudianteReply\x12,\n\x11ListarEstudiantes\x12\x06.Empty\x1a\x0f.EstudianteList\x12\x35\n\x0f\x43rearEstudiante\x12\x10.EstudianteReply\x1a\x10.EstudianteReply\x12\x37\n\x10\x42orrarEstudiante\x12\x12.EstudianteRequest\x1a\x0f.DeleteResponseB/\n\x13\x65\x64u.pucmm.eict.grpcB\x16\x45studianteServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asignacion_aula_7_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023edu.pucmm.eict.grpcB\026EstudianteServiceProtoP\001'
  _globals['_ESTUDIANTEREQUEST']._serialized_start=27
  _globals['_ESTUDIANTEREQUEST']._serialized_end=65
  _globals['_ESTUDIANTEREPLY']._serialized_start=67
  _globals['_ESTUDIANTEREPLY']._serialized_end=119
  _globals['_ESTUDIANTELIST']._serialized_start=121
  _globals['_ESTUDIANTELIST']._serialized_end=176
  _globals['_DELETERESPONSE']._serialized_start=178
  _globals['_DELETERESPONSE']._serialized_end=226
  _globals['_EMPTY']._serialized_start=228
  _globals['_EMPTY']._serialized_end=235
  _globals['_ESTUDIANTESERVICE']._serialized_start=238
  _globals['_ESTUDIANTESERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
