# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import urlshortener_pb2 as urlshortener__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in urlshortener_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UrlShortenerServiceStub(object):
    """*
    Service for managing URL shortening and retrieval.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUserUrls = channel.unary_unary(
                '/UrlShortenerService/ListUserUrls',
                request_serializer=urlshortener__pb2.ListUserUrlsRequest.SerializeToString,
                response_deserializer=urlshortener__pb2.ListUserUrlsResponse.FromString,
                _registered_method=True)
        self.CreateUrl = channel.unary_unary(
                '/UrlShortenerService/CreateUrl',
                request_serializer=urlshortener__pb2.CreateUrlRequest.SerializeToString,
                response_deserializer=urlshortener__pb2.CreateUrlResponse.FromString,
                _registered_method=True)


class UrlShortenerServiceServicer(object):
    """*
    Service for managing URL shortening and retrieval.
    """

    def ListUserUrls(self, request, context):
        """*
        Retrieves a list of URLs associated with a specific user.
        @param ListUserUrlsRequest - The request containing the user ID.
        @return ListUserUrlsResponse - The response containing the list of URLs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUrl(self, request, context):
        """*
        Creates a shortened URL for a given original URL.
        @param CreateUrlRequest - The request containing the user ID and original URL.
        @return CreateUrlResponse - The response containing the shortened URL and metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrlShortenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUserUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserUrls,
                    request_deserializer=urlshortener__pb2.ListUserUrlsRequest.FromString,
                    response_serializer=urlshortener__pb2.ListUserUrlsResponse.SerializeToString,
            ),
            'CreateUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUrl,
                    request_deserializer=urlshortener__pb2.CreateUrlRequest.FromString,
                    response_serializer=urlshortener__pb2.CreateUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UrlShortenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UrlShortenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UrlShortenerService(object):
    """*
    Service for managing URL shortening and retrieval.
    """

    @staticmethod
    def ListUserUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UrlShortenerService/ListUserUrls',
            urlshortener__pb2.ListUserUrlsRequest.SerializeToString,
            urlshortener__pb2.ListUserUrlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UrlShortenerService/CreateUrl',
            urlshortener__pb2.CreateUrlRequest.SerializeToString,
            urlshortener__pb2.CreateUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
