/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.controllers.ArticleController;
import org.example.controllers.CommentController;
import org.example.controllers.TagController;
import org.example.controllers.UserController;

import io.javalin.Javalin;
import io.javalin.rendering.template.JavalinThymeleaf;

public class App {
    /**
     * @param args
     */
    public static void main(String[] args) {

        var app = Javalin.create(config -> {
            config.staticFiles.add(cf -> {
                cf.hostedPath = "/";
                cf.directory = "/public";

            });
            config.staticFiles.add(cf -> {
                cf.hostedPath = "/assets";
                cf.directory = "/assets";

            });
            config.staticFiles.add(cf -> {
                cf.hostedPath = "/fragments";
                cf.directory = "/fragments";

            });

            config.fileRenderer(new JavalinThymeleaf());
        }).start(7777);

        app.before("/", ctx -> {
        });

        app.get("/articles", ArticleController::getAllArticles);
        app.get("/articles/{id}", ArticleController::getArticleById);
        app.post("/articles", ArticleController::createArticle);
        app.post("/articles/{id}", ArticleController::updateArticle);
        app.delete("/articles/{id}", ArticleController::deleteArticle);

        app.get("/users", UserController::getAllUsers);
        app.get("/users/{username}", UserController::getUserByUsername);
        app.post("/users/", UserController::createUser);
        app.put("/users/{username}", UserController::updateUser);
        app.delete("/users/{username}", UserController::deleteUser);

        app.get("/comments", CommentController::getAllComments);
        app.get("/comments/{id}", CommentController::getCommentById);
        app.post("/comments", CommentController::createComment);
        app.put("/comments/{id}", CommentController::updateComment);
        app.delete("/comments/{id}", CommentController::deleteComment);
        app.get("/articles/{articleId}/comments/{commentId}", CommentController::getCommentByArticleAndCommentId);

        app.post("/tags", TagController::createTag);

        new ArticleController(app).applyRoutes();

    }
}
