/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.javalin.Javalin;
import org.example.controllers.ArticleController;

public class App {
	public static void main(String[] args) {

		var app = Javalin.create().start(7777);

		app.get("/articles", ArticleController::getAllArticles);
		app.post("/articles",ArticleController::createArticle);


	}
}
